---
- name: Setup system
  hosts: target
  roles:
    - role: est
      tags: est
    - role: kontza.server_setup_helpers.generic
      tags: generic
      become: yes
    - role: kontza.server_setup_helpers.ssmtp
      tags: ssmtp
      become: yes
    - role: kontza.server_setup_helpers.autoupdates
      tags: autoupdates
      become: yes
    - role: podman
      tags: podman
      become: yes
    - role: systemd-resolved
      tags: systemd-resolved
      become: yes
    - role: ufw
      tags: ufw
      become: yes
    - role: pihole
      tags: pihole
      become: yes
