---
- name: Setup Siurvahti
  hosts: target
  vars:
    rhel_world: ['Fedora']
  roles:
    - role: est
      tags: est
    - role: generic
      tags: generic
      become: yes
    - role: podman
      tags: podman
      become: yes
    - role: systemd-resolved
      tags: systemd-resolved
      become: yes
    - role: ufw
      tags: ufw
      become: yes
    - role: pihole
      tags: pihole
      become: yes
    - role: autoupdates
      tags: autoupdates
      become: yes