---
- name: Setup Siurvahti
  hosts: target
  roles:
    - role: est
      tags: est
    - role: generic
      tags: generic
      become: yes
    - role: podman
      tags: podman
      become: yes
    - role: systemd-resolved
      tags: systemd-resolved
      become: yes
    - role: nft
      tags: nft
      become: yes
    - role: pihole
      tags: pihole
      become: yes