---
- name: Setup system
  hosts: target
  roles:
    - role: est
      tags: est
    - role: generic
      tags: generic
      become: yes
    - role: msmtp
      tags: msmtp
      become: yes
    - role: firewalld
      tags: firewalld
      become: yes
    - role: pihole
      tags: pihole
      become: yes
