---
- name: Setup Siurvahti
  hosts: target
  roles:
    - role: est
      tags: est
    - role: generic
      tags: generic
    - role: podman
      tags: podman
    - role: systemd-resolved
      tags: systemd-resolved
    - role: ufw
      tags: ufw
      become: yes
    - role: pihole
      tags: pihole