---
- name: Setup system
  hosts: target
  roles:
    - role: est
      tags: est
    - role: kontza.server_setup_helpers.generic
      tags: generic
      become: yes
    - role: kontza.server_setup_helpers.msmtp
      tags: msmtp
      become: yes
    - role: kontza.server_setup_helpers.firewalld
      tags: firewalld
      become: yes
    - role: firewalld
      tags: firewalld
      become: yes
    # - role: pihole
    #   tags: pihole
    #   become: yes
