#!/bin/sh
BECOME_SCRIPT=./scripts/become-pass
if test -n "$CUSTOM_BECOME";then
    BECOME_SCRIPT="$CUSTOM_BECOME"
fi
ansible-playbook \
    --become-password-file $BECOME_SCRIPT \
    --vault-password-file ./scripts/vault-pass \
    ./install.yaml \
    $@
