---
- name: Setup otsonkolo
  hosts: target
  roles:
    - role: est
      tags: est
    - role: generic
      tags: generic
      become: yes
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    # - role: msmtp
    #   tags: msmtp
    #   become: yes
    # - role: users
    #   tags: users
    #   become: yes
    # - role: samba
    #   tags: samba
    #   become: yes
