---
- name: Install packages related to unattended upgrades
  ansible.builtin.package:
    name: "{{item}}"
    state: latest
  loop:
    - ssmtp
    - mailutils

- name: Install ssmtp config
  ansible.builtin.copy:
    dest: /etc/ssmtp/ssmtp.conf
    content: |
      root={{notification.recipient}}
      mailhub=smtp.gmail.com:587
      rewriteDomain=gmail.com
      hostname={{inventory_hostname}}
      AuthUser={{notification.sender}}
      AuthPass={{notification.password}}
      UseSTARTTLS=Yes

- name: Install local username aliases for ssmtp
  ansible.builtin.copy:
    dest: /etc/ssmtp/revaliases
    content: |
      root:{{notification.sender}}:smtp.gmail.com:587
      {{ansible_user}}:{{notification.sender}}:smtp.gmail.com:587

- name: Set full usernames
  ansible.builtin.command:
    cmd: chfn -f '{{item}} at {{inventory_hostname}}' {{item}}
  loop:
    - root
    - "{{ansible_user}}"
