---
# This file is a placeholder for est-tags: tasks that are
# meant to be run with '-test'.

- name: Inventory vars
  ansible.builtin.debug:
    var: item
  tags:
    - never
  loop:
    - "{{inventory_file|basename}}"
    - "{{inventory_hostname}}"