---
- name: Install Podman
  become: yes
  ansible.builtin.package:
    name: podman
    state: latest
    update_cache: yes
  tags:
    - podman

- name: Ensure quay.io and docker.io are included in search
  become: yes
  ansible.builtin.blockinfile:
    path: /etc/containers/registries.conf
    block: |
      [registries.search]
      registries = ['docker.io']
    # registries = ['quay.io', 'docker.io']
  tags:
    - podman
