---
- name: Install Podman
  ansible.builtin.package:
    name: podman
    state: latest
    update_cache: yes

- name: Ensure docker.io is included in image search
  ansible.builtin.blockinfile:
    path: /etc/containers/registries.conf
    block: |
      [registries.search]
      registries = ['docker.io']
