---
- name: Add stock users
  ansible.builtin.user:
    name: "{{item}}"
    home: "/raid/home/{{item}}"
    create_home: false
    state: present
    shell: /usr/bin/fish
  loop: "{{(otsonkolo.users.keys()|list)[1:]}}"

# {% for user, password_hash in otsonkolo.users.items() %}
# {% if 'root' != user %}
#   - name: Create group '{{user}}'
#     ansible.builtin.group:
#       name: {{user}}
#       gid: {{otsonkolo.userids[loop.index0]}}
#       state: present

#   - name: Create '{{user}}'
#     ansible.builtin.user:
#       name: {{user}}
#       uid: {{otsonkolo.userids[loop.index0]}}
#       password: "{{password_hash}}"
#       home: /opt/raid/{{user}}
#       shell: /usr/bin/fish

#   - name: Make sure '{{user}}' has '.ssh'
#     ansible.builtin.file:
#       path: /opt/raid/{{user}}/.ssh
#       state: directory
#       owner: {{user}}
#       group: {{user}}

#   - name: Fix /opt/raid/{{user}} ownership
#     ansible.builtin.file:
#       path: /opt/raid/{{user}}
#       owner: {{user}}
#       group: {{user}}
#       state: directory
#       recurse: yes

# {% endif %}
# {% endfor %}
