---
- name: Add pihole user
  become: yes
  ansible.builtin.user:
    name: "{{pihole.user}}"
    home: "{{pihole.home}}"
    shell: /bin/false
  tags:
    - pihole

- name: Create directories for container
  become: yes
  ansible.builtin.file:
    path: "{{pihole.home}}/{{item}}"
    state: directory
    owner: "{{pihole.user}}"
    group: "{{pihole.group}}"
  loop:
    - etc-pihole
    - etc-dnsmasq.d
    - systemd
  tags:
    - pihole

- name: Install ACL in preparation for the next task (enable lingering)
  become: yes
  ansible.builtin.package:
    name: acl
    state: latest
  tags:
    - pihole

- name: Enable lingering for {{pihole.user}}
  become: yes
  ansible.builtin.command:
    cmd: loginctl enable-linger {{pihole.user}}
  tags:
    - pihole

- name: Create the Pi-hole container
  become: yes
  become_user: "{{pihole.user}}"
  retries: 3
  containers.podman.podman_container:
    name: pihole
    image: pihole/pihole
    state: present
    recreate: yes
    ports:
      - "10053:53/tcp"
      - "10053:53/udp"
      - "10067:67/udp"
      - "10080:80/tcp"
    env:
      TZ: "Europe/Helsinki"
      WEBPASSWORD: "{{pihole.webpassword}}"
    volumes:
      - "{{pihole.home}}/etc-pihole/:/etc/pihole"
      - "{{pihole.home}}/etc-dnsmasq.d:/etc/dnsmasq.d"
    cap_add:
      - NET_ADMIN
    generate_systemd:
      path: "{{pihole.home}}/systemd"
  register: creation_result

- name: Extract created systemd unit file's name
  ansible.builtin.set_fact:
    unit_file: "{{(creation_result['podman_systemd'].keys()|list)[0]}}"

- name: Ensure the systemd unit file is rootless
  become: yes
  become_user: "{{pihole.user}}"
  ansible.builtin.blockinfile:
    path: "{{pihole.home}}/systemd/{{unit_file}}.service"
    insertafter: ^\[Service\]
    block: |
      User={{pihole.user}}
      Group={{pihole.group}}

- name: Disable lingering for {{pihole.user}}
  become: yes
  ansible.builtin.command:
    cmd: loginctl disable-linger {{pihole.user}}
