---
- name: Add pihole user
  become: yes
  ansible.builtin.user:
    name: "{{pihole.user}}"
    home: "{{pihole.home}}"
    shell: /bin/false
  tags:
    - pihole

- name: Create directories for container volumes
  become: yes
  ansible.builtin.file:
    path: "{{pihole.home}}/{{item}}"
    state: directory
    owner: "{{pihole.user}}"
    group: "{{pihole.user}}"
  loop:
    - etc-pihole
    - etc-dnsmasq.d
  tags:
    - pihole

- name: Install ACL in preparation for the next task
  become: yes
  ansible.builtin.package:
    name: acl
    state: latest
  tags:
    - pihole

- name: Create the Pi-hole container
  become: yes
  become_user: "{{pihole.user}}"
  containers.podman.podman_container:
    name: pihole
    image: pihole/pihole
    state: present
    recreate: yes
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    env:
      TZ: "Europe/Helsinki"
      WEBPASSWORD: "{{pihole.webpassword}}"
    volumes:
      - "{{pihole.home}}/etc-pihole/:/etc/pihole"
      - "{{pihole.home}}/etc-dnsmasq.d:/etc/dnsmasq.d"
    cap_add:
      - NET_ADMIN
  tags:
    - pihole
